version: '3'
services:
  goldtalk_api:
    build: .
    image: goldtalk_img:${TAG}
    container_name: goldtalkAPI
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV_TAG=prd
    volumes:
      - /tmp/aaa:/app/output/log