definitions:
  model.PriceInfo:
    properties:
      normal:
        type: number
      trial:
        type: number
    type: object
  service.TutorListByLang:
    properties:
      data:
        items:
          $ref: '#/definitions/model.PriceInfo'
        type: array
      lastUpdate:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/test/{language}:
    get:
      consumes:
      - application/json
      operationId: '###@@@'
      parameters:
      - description: language
        in: path
        name: language
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.TutorListByLang'
      summary: 測試用
      tags:
      - 第一類
swagger: "2.0"
